### ISSUE TITLE
Custom exceptions conflict with sanic's

### ISSUE THREAD

**Issue by eltrhn** [ahopkins/sanic-jwt#77]
```python
>>> import sanic, sanic_jwt
>>> sanic.exceptions.abort(401)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/src/sanic/sanic/exceptions.py", line 288, in abort
    raise sanic_exception(message=message, status_code=status_code)
TypeError: __init__() got an unexpected keyword argument 'status_code'
```

Printing out the exception before this problem line shows that it's attempting to raise `sanic_jwt.exceptions.AuthenticationFailed` rather than `sanic.exceptions.Unauthorized`. Looks like the `@add_status_code(...)` deco just puts status_code/cls as key/value in a dict, so adding the same status code more than once overwrites its previous value.

This occurs both in pre-1.0 and in the current dev branch. Would it be ameliorable on sanic_jwt's end?

**Comment by eltrhn** [comment]
Looks like it's 'fixable' by inheriting manually from each Sanic exception class, in lieu of the decorator...

```python
from sanic import exceptions as excep


class SanicJWTException(excep.SanicException):
    pass


class AuthenticationFailed(excep.Unauthorized):
    def __init__(self, message="Authentication failed."):
        super().__init__(message)


class MissingAuthorizationHeader(excep.InvalidUsage):
    ...
```
...but it feels a tad clunky and I'm not yet familiar enough with either library to know if there's a better solution. Does this look okay?

**Comment by eltrhn** [comment]
Awesome. Thank you!
